// Telemetry Postgres schema for the WorkWise processing pipeline (Phase 2).
//
// Two layers:
//   - raw_events (daily range-partitioned, 30-day retention) + interaction_minutes
//     + sessions + user_status   -> written at ingest
//   - daily_* rollups + task_spans + daily_team_stats   -> written by the rollup job
//   - raw_log_access_audit  -> who viewed whose raw logs (governance)
//
// All DDL is idempotent (CREATE ... IF NOT EXISTS) so it is safe to run on boot.

// --- partition helpers ---------------------------------------------------

// 'YYYY-MM-DD' for the UTC day of a Date (REPORT_TZ defaults to UTC for now).
export function dayKey(date) {
  return date.toISOString().slice(0, 10)
}

function nextDayKey(dayStr) {
  const d = new Date(dayStr + "T00:00:00.000Z")
  d.setUTCDate(d.getUTCDate() + 1)
  return dayKey(d)
}

const DAY_RE = /^\d{4}-\d{2}-\d{2}$/

// Create the daily partition of raw_events for `dayStr` if it doesn't exist.
// dayStr is always derived internally (never user input); validated anyway.
export async function ensureRawPartition(pool, dayStr) {
  if (!DAY_RE.test(dayStr)) throw new Error(`bad day key: ${dayStr}`)
  const from = dayStr
  const to = nextDayKey(dayStr)
  const part = `raw_events_p_${dayStr.replace(/-/g, "")}`
  await pool.query(
    `CREATE TABLE IF NOT EXISTS ${part} PARTITION OF raw_events
       FOR VALUES FROM ('${from}') TO ('${to}')`
  )
}

// --- schema --------------------------------------------------------------

export async function initializeTelemetryTables(pool) {
  // Pre-launch reset: drop the old raw-everything tables. Guarded so it only
  // ever fires when explicitly asked (never on a normal production boot).
  if (process.env.TELEMETRY_RESET === "1") {
    await pool.query(`DROP TABLE IF EXISTS activity_logs`)
    await pool.query(`DROP TABLE IF EXISTS task_events`)
  }

  // raw_events: authoritative short-retention store, partitioned by day so
  // retention is a partition DROP (no bloat) and date scans get pruned.
  // PK must include the partition key (day).
  await pool.query(`
    CREATE TABLE IF NOT EXISTS raw_events (
      id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
      email           TEXT        NOT NULL,
      event_type      TEXT        NOT NULL,
      ts              TIMESTAMPTZ NOT NULL,
      day             DATE        NOT NULL,
      url             TEXT,
      domain          TEXT,
      encord_category TEXT,
      project_id      TEXT,
      data_id         TEXT,
      metadata        JSONB,
      ingested_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (id, day)
    ) PARTITION BY RANGE (day)
  `)
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_raw_email_day      ON raw_events (email, day)`)
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_raw_day            ON raw_events (day)`)
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_raw_email_day_type ON raw_events (email, day, event_type)`)
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_raw_data_id        ON raw_events (data_id) WHERE data_id IS NOT NULL`)

  // Folded high-volume interactions (one row per email per minute).
  await pool.query(`
    CREATE TABLE IF NOT EXISTS interaction_minutes (
      email           TEXT        NOT NULL,
      minute          TIMESTAMPTZ NOT NULL,
      day             DATE        NOT NULL,
      click_count     INTEGER     NOT NULL DEFAULT 0,
      shortcut_count  INTEGER     NOT NULL DEFAULT 0,
      keypress_events INTEGER     NOT NULL DEFAULT 0,
      keystroke_count INTEGER     NOT NULL DEFAULT 0,
      PRIMARY KEY (email, minute)
    )
  `)
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_interaction_day ON interaction_minutes (email, day)`)

  // Completed sessions (one row per SESSION_STOPPED, client-computed totals).
  await pool.query(`
    CREATE TABLE IF NOT EXISTS sessions (
      id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email         TEXT NOT NULL,
      day           DATE NOT NULL,
      started_at    TIMESTAMPTZ,
      stopped_at    TIMESTAMPTZ NOT NULL,
      total_ms      BIGINT,
      active_ms     BIGINT,
      paused_ms     BIGINT,
      pause_count   INTEGER,
      total_events  INTEGER,
      pause_history JSONB,
      dedupe_key    TEXT UNIQUE
    )
  `)
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_sessions_email_day ON sessions (email, day)`)

  // Cheap live-status read model (upserted on every batch).
  await pool.query(`
    CREATE TABLE IF NOT EXISTS user_status (
      email           TEXT PRIMARY KEY,
      last_event_at   TIMESTAMPTZ NOT NULL,
      last_idle_state TEXT,
      session_open    BOOLEAN NOT NULL DEFAULT false,
      updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `)

  // --- rollup tables (populated by the rollup job, read by the dashboard) ---
  await pool.query(`
    CREATE TABLE IF NOT EXISTS daily_user_stats (
      email         TEXT NOT NULL,
      day           DATE NOT NULL,
      active_ms     BIGINT  NOT NULL DEFAULT 0,
      paused_ms     BIGINT  NOT NULL DEFAULT 0,
      session_count INTEGER NOT NULL DEFAULT 0,
      pause_count   INTEGER NOT NULL DEFAULT 0,
      focus_ratio   REAL,
      tasks_started INTEGER NOT NULL DEFAULT 0,
      tasks_skipped INTEGER NOT NULL DEFAULT 0,
      tasks_exited  INTEGER NOT NULL DEFAULT 0,
      avg_task_ms   BIGINT,
      first_active  TIMESTAMPTZ,
      last_active   TIMESTAMPTZ,
      updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (email, day)
    )
  `)
  await pool.query(`
    CREATE TABLE IF NOT EXISTS daily_domain_time (
      email     TEXT NOT NULL,
      day       DATE NOT NULL,
      domain    TEXT NOT NULL,
      active_ms BIGINT NOT NULL DEFAULT 0,
      PRIMARY KEY (email, day, domain)
    )
  `)
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_domain_time_day ON daily_domain_time (email, day)`)
  await pool.query(`
    CREATE TABLE IF NOT EXISTS daily_encord_section_time (
      email     TEXT NOT NULL,
      day       DATE NOT NULL,
      category  TEXT NOT NULL,
      active_ms BIGINT NOT NULL DEFAULT 0,
      PRIMARY KEY (email, day, category)
    )
  `)
  await pool.query(`
    CREATE TABLE IF NOT EXISTS daily_event_counts_hourly (
      email      TEXT NOT NULL,
      day        DATE NOT NULL,
      hour       SMALLINT NOT NULL,
      event_type TEXT NOT NULL,
      cnt        INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY (email, day, hour, event_type)
    )
  `)
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_evt_counts_day ON daily_event_counts_hourly (day)`)
  await pool.query(`
    CREATE TABLE IF NOT EXISTS task_spans (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email       TEXT NOT NULL,
      day         DATE NOT NULL,
      project_id  TEXT,
      data_id     TEXT,
      started_at  TIMESTAMPTZ,
      ended_at    TIMESTAMPTZ,
      duration_ms BIGINT,
      outcome     TEXT,
      dedupe_key  TEXT UNIQUE
    )
  `)
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_task_spans_email_day ON task_spans (email, day)`)
  await pool.query(`
    CREATE TABLE IF NOT EXISTS daily_team_stats (
      day               DATE PRIMARY KEY,
      active_annotators INTEGER NOT NULL DEFAULT 0,
      team_active_ms    BIGINT  NOT NULL DEFAULT 0,
      tasks_started     INTEGER NOT NULL DEFAULT 0,
      tasks_skipped     INTEGER NOT NULL DEFAULT 0,
      skip_rate         REAL,
      focus_ratio       REAL,
      avg_session_ms    BIGINT,
      updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `)

  // Governance: every view of an employee's raw logs is recorded.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS raw_log_access_audit (
      id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      viewer_email TEXT NOT NULL,
      viewed_email TEXT NOT NULL,
      viewed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
      ip           TEXT
    )
  `)

  // Per-employee work-site classification + colors (set by managers in the dashboard).
  await pool.query(`
    CREATE TABLE IF NOT EXISTS work_sites (
      email      TEXT NOT NULL,
      domain     TEXT NOT NULL,
      is_work    BOOLEAN NOT NULL DEFAULT true,
      color      TEXT,
      label      TEXT,
      updated_by TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (email, domain)
    )
  `)

  // Make sure today's (and tomorrow's) raw partitions exist up front.
  const today = dayKey(new Date())
  await ensureRawPartition(pool, today)
  await ensureRawPartition(pool, nextDayKey(today))

  console.log("Telemetry Postgres schema initialized (Phase 2).")
}
